# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dan Park
tagline:             'Learning the hard way... sometimes'
description:         'Cool sidebar!'
url:                 https://danpark487.github.io
baseurl:             ''
paginate:            5
paginate_path:       'page:num'

# About/contact
author:
  name:              Daniel Park
  url:               https://danpark487.github.io
  email:             danielpark.487@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist